version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Extensions.Configuration.Abstractions
  - dependency-name: Microsoft.Extensions.Configuration.Json
  - dependency-name: Microsoft.Extensions.DependencyInjection
  - dependency-name: Microsoft.Extensions.Hosting
  - dependency-name: Microsoft.Extensions.Hosting.Abstractions
  - dependency-name: Microsoft.Extensions.Logging
  - dependency-name: Microsoft.Extensions.Logging.Abstractions
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - "> 16.2.0, < 17"
