version: 1.0.{build}
configuration: Release
build_script:
- ps: >-
    dotnet restore src\NLog.Extensions.Logging

     .\patchFileVersion.ps1 "NLog.Extensions.Logging.csproj" "$env:appveyor_build_version"

    dotnet pack src\NLog.Extensions.Logging --configuration Release
artifacts:
- path: 'src\NLog.Extensions.Logging\bin\release\*.nupkg'

test_script:
- ps: .\run-tests.ps1

deploy:
- provider: NuGet
  api_key:
    secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
  artifact: /.*\.nupkg/
  on:
    branch: master
