version: 1.0.{build}
configuration: Release
build_script:
- ps: >-
    dotnet restore src\NLog.Extensions.Logging

    dotnet pack src\NLog.Extensions.Logging --configuration Release
artifacts:
- path: 'src\NLog.Extensions.Logging\bin\release\*.nupkg'
