version: 1.0.{build}
configuration: Release
before_build:
- cmd: >-
    dnvm install latest
    
    dnu restore --quiet
build:
  project: NLog.Extensions.Logging.sln
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
